version: '3.5'
services:
  main:
    build:
      context: ./
    restart: always
    environment:
      PORT: ${PORT}
    # ports:
    # - "${PORT}:80"
    networks:
      - nginx_backend

networks:
  nginx_backend:
    name: nginx_backend